name: My Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run my custom action1
          uses: .../action/index
          with:
            name: Timor88
      - name: Run my custom action2
        uses: .../action/action
        with:
          name: Timor88
