name: My Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          name: Timor88
      - name: Run script
        run: |
          echo "Hello, world!"
          echo "This is a script executed by GitHub Actions."
