name: My Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run1
        uses: .../action/index
        with:
          name: Timor88
      - name: Run2
        uses: .../action/action
        with:
          name: Timor88
